### ISSUE TITLE
[-v] c7n_mailer - Readme test - Error

### ISSUE THREAD

**Issue by whit537** [whit537/cloud-custodian#49]
https://github.com/capitalone/cloud-custodian/issues/1780

**Comment by whit537** [comment]
>Hi!
>
>I am trying to test the c7n-mailer using the example mailer.yml and test-policy.yml in the readme. >The Lambda deploys but when it runs I see the following error in the cloud watch logs:
>
>```
>('Unknown resource type', u'sqs')
>```
>
>Followed by:
>
>
>```
> [ERROR]	2017-11-13T15:02:42.369Z	b27a74a0-c883-11e7-a5ad-53eada5f2f8b	Error starting mailer MailerSqsQueueProcessor(). 
> Error: unicode argument expected, got 'str' 
>
> Traceback (most recent call last):
> File "/var/task/c7n_mailer/handle.py", line 52, in start_c7n_mailer
>   mailer_sqs_queue_processor.run(parallel)
> File "/var/task/c7n_mailer/sqs_queue_processor.py", line 122, in run
>   self.process_sqs_messsage(sqs_message)
> File "/var/task/c7n_mailer/sqs_queue_processor.py", line 148, in process_sqs_messsage
>   to_addrs_to_email_messages_map = >    email_delivery.get_to_addrs_email_messages_map(sqs_message)
> File "/var/task/c7n_mailer/email_delivery.py", line 144, in get_to_addrs_email_messages_map
>   list(to_addrs)
> File "/var/task/c7n_mailer/email_delivery.py", line 170, in get_mimetext_message
>   body = get_rendered_jinja(to_addrs, sqs_message, resources, self.logger)
> File "/var/task/c7n_mailer/utils.py", line 62, in get_rendered_jinja
>   region=sqs_message.get('region', ''))
> File "/var/task/jinja2/environment.py", line 1008, in render
>   return self.environment.handle_exception(exc_info, True)
> File "/var/task/jinja2/environment.py", line 780, in handle_exception
>   reraise(exc_type, exc_value, tb)
> File "/var/task/msg-templates/default.j2", line 5, in top-level template code
>   {{ format_resource(resource, policy['resource']) }}
> File "/var/task/c7n_mailer/utils.py", line 272, in resource_format
>   return "%s" % format_struct(resource)
> File "/var/task/c7n_mailer/utils.py", line 115, in format_struct
>   json.dump(evt, buf, indent=2)
> File "/usr/lib64/python2.7/json/__init__.py", line 190, in dump
>   fp.write(chunk)
> TypeError: unicode argument expected, got 'str'
>```
>
>Please can you help? I've attached my YAML files. 
>
>[files.zip](https://github.com/capitalone/cloud-custodian/files/1467357/files.zip)

**Comment by whit537** [comment]
Okay, repro'd.

**Comment by whit537** [comment]
🤔

```
{ u'ApproximateNumberOfMessagesNotVisible': u'0'
, u'QueueUrl': u'https://eu-west-1.queue.amazonaws.com/644160558196/test-mailer'
, u'MessageRetentionPeriod': u'345600'
, u'ApproximateNumberOfMessagesDelayed': u'0'
, u'c7n:MatchedFilters': [u'tag:MailerTest']
, u'MaximumMessageSize': u'262144'
, u'CreatedTimestamp': u'1510651500'
, u'ApproximateNumberOfMessages': u'0'
, u'ReceiveMessageWaitTimeSeconds': u'0'
, u'DelaySeconds': u'0'
, u'VisibilityTimeout': u'30'
, u'LastModifiedTimestamp': u'1510651500'
, u'QueueArn': u'arn:aws:sqs:eu-west-1:644160558196:test-mailer'
 }
```

```diff
diff --git a/tools/c7n_mailer/c7n_mailer/utils.py b/tools/c7n_mailer/c7n_mailer/utils.py
index 04be400..f2b74ce 100644
--- a/tools/c7n_mailer/c7n_mailer/utils.py
+++ b/tools/c7n_mailer/c7n_mailer/utils.py
@@ -111,6 +111,7 @@ def get_date_time_delta(delta):
 
 def format_struct(evt):
     buf = StringIO()
+    print(evt)
     json.dump(evt, buf, indent=2)
     return buf.getvalue()
 
```

**Comment by whit537** [comment]
```
{ u'ApproximateNumberOfMessagesNotVisible': u'0'
, u'QueueUrl': u'https://eu-west-1.queue.amazonaws.com/644160558196/test-mailer'
, u'MessageRetentionPeriod':                u'345600'
, u'ApproximateNumberOfMessagesDelayed':    u'0'
, u'c7n:MatchedFilters':           [u'tag:MailerTest']
, u'MaximumMessageSize':            u'262144'
, u'CreatedTimestamp':              u'1510651500'
, u'ApproximateNumberOfMessages':   u'0'
, u'ReceiveMessageWaitTimeSeconds': u'0'
, u'DelaySeconds':             u'0'
, u'VisibilityTimeout':        u'30'
, u'LastModifiedTimestamp':    u'1510651500'
, u'QueueArn':                 u'arn:aws:sqs:eu-west-1:644160558196:test-mailer'
 }
```

**Comment by whit537** [comment]
Yeah, this is fixed in https://github.com/capitalone/cloud-custodian/pull/1417.

**Comment by stevelaver** [comment]
Thanks guys for the quick response!
